title: "Pragmatical AI"
name: "Peter Went"
theme: jekyll-theme-minimal
description: "Data science rōnin. 浪人 Analytics, machine learning, and alternative data. Yoga."
logo: "/assets/images/88x88.png"

linkedin: www.linkedin.com/in/pwent
twitter: @thePeterWent
medium: medium.com/@peterwent

breadcrumbs: true
read_time: true
search: true
