title: "Thoughts about AI"
name: "Peter Went"
theme: jekyll-theme-minimal
description: "Thoughts around intelligence: human, artifical and societal."
logo: "/assets/images/88x88.png"

linkedin: www.linkedin.com/in/pwent
twitter: @thePeterWent
medium: medium.com/@peterwent

breadcrumbs: true
read_time: true
search: true
